### ISSUE TITLE
Add # of kids fed to the !giving command

### ISSUE THREAD

**Issue by mholloway24** [MichaelJolley/vulcan#35]
When the giving command is entered, add the current number of kids fed on the current stream/month/all-time.

**Comment by mholloway24** [comment]
Vulcan will need to calculate the # of kids fed with every cheer and sub. This could also be stored on the stream object in the db.

**Comment by MichaelJolley** [comment]
@all-contributors please add @mholloway24 for ideas

**Comment by MichaelJolley** [comment]
@mholloway24 handling a different way.  How? You'll see on the next stream. 😄
