### ISSUE TITLE
Overlay is showing streak months for subs rather then actual months subbed

### ISSUE THREAD

**Issue by cmjchrisjones** [MichaelJolley/vulcan#49]
Today when @electrichavoc resubbed (about 3 hours 4 minutes into the stream), the new overlay showed that it was 11 months, however, the Twitch channel showed it as 12 months. The 11 months was from the stream streak rather than the total amount of months subbed.

**Comment by MichaelJolley** [comment]
@allcontributors please add @cmjchrisjones for bugs
