### ISSUE TITLE
Stream Service

### ISSUE THREAD

**Issue by MichaelJolley** [MichaelJolley/vulcan#5]
Need a stream service to live in the Persistent Services.

It will likely be an Node.js express app serving endpoints and also subscribing to SignalR to process messages:

#### GET: /stream/:streamDate

Retrieves the stream from FaunaDB based on the `streamDate` and returns it as JSON.  If no stream for that date is found, returns 404.

---

#### streamStart

Looks to see if a stream exists for that stream's `started_at` property. If not, creates the record in FaunaDB.

#### streamUpdated

Looks to see if a stream exists for that stream's `started_at` property. If not, creates the record in FaunaDB.  If it does, update the title of the stream.

#### streamEnd

Looks to see if a stream exists for that stream's `started_at` property. If not, creates the record in FaunaDB with an `ended_at` property of now.  If it does exist, sets an `ended_at` property to be now.

**Comment by MichaelJolley** [comment]
@all-contributors please add @RobinMalfait for code

**Comment by RobinMalfait** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/469d4aea-0aaa-4b89-919e-0fd853b6f0f0-888d7782-1474-482e-8588-de4fda5de576-v1.png?transparent=1&palette=1&width=246)
