### ISSUE TITLE
Add ability to allow chat members to bust the cache from Twitch

### ISSUE THREAD

**Issue by cmjchrisjones** [MichaelJolley/vulcan#50]
In the old IO bot, chat users could issue `!profile update` or `!profile refresh` (I can't remember). Vulcan needs the same availability for when users update their profile pictures etc.

**Comment by MichaelJolley** [comment]
@allcontributors please add @nihonjinrxs for tests and code

**Comment by MichaelJolley** [comment]
@allcontributors please add @redet-G for tests and code

**Comment by MichaelJolley** [comment]
Rather than provide an update command we are updating the user each time they arrive at a stream.  Thanks for recording this @cmjchrisjones
