### ISSUE TITLE
Better formatting of uptime

### ISSUE THREAD

**Issue by nihonjinrxs** [MichaelJolley/vulcan#53]
In-stream (where I'm CodeAndData), you mentioned a desire for better formatting of the duration than [this line](https://github.com/MichaelJolley/vulcan/blob/7a2b2a6176367fa0d3ead8ebf600cb1597b41a86/src/functions/chat/Uptime/index.js#L45).

Unfortunately, moment.js doesn't support doing that directly and [has rebuffed requests so far to implement such a feature](https://github.com/moment/moment/issues/348), so it's a roll-your-own. I tend to just code that stuff up myself than to try to find some third party plugin, so...

I played around with that and got to [this CodePen](https://codepen.io/nihonjinrxs/pen/QWjMJdp), which I think is pretty nice. Feel free to use or modify as you like.

**Comment by MichaelJolley** [comment]
@allcontributors please add @nihonjinrxs for code

**Comment by MichaelJolley** [comment]
Thanks for the help @nihonjinrxs!  We got it working on stream today!
